### ISSUE TITLE
Control Gain

### ISSUE THREAD

**Issue by ahmedosama9777** [FLIR/rawBoson#12]
Hello, 

I am not sure what is the command to control the high/low gain of the Flir Boson, can you guide me through this?

**Comment by ahmedosama9777** [comment]
After doing some extra research, I found this document: https://www.flir.com/globalassets/imported-assets/document/boson_sdk_documentation_9hz-v11412-and-later.pdf

Using it, I was able to get the right command to use to switch between high, low and automatic gain modes.
The commands are: 
rawBoson -p/dev/ttyAMC0 -b921600 c00050014 x0 x0 x0 x0 = FLR_BOSON_HIGH_GAIN
rawBoson -p/dev/ttyAMC0 -b921600 c00050014 x0 x0 x0 x1 = FLR_BOSON_LOW_GAIN
rawBoson -p/dev/ttyAMC0 -b921600 c00050014 x0 x0 x0 x2 = FLR_BOSON_AUTO_GAIN
rawBoson -p/dev/ttyAMC0 -b921600 c00050014 x0 x0 x0 x3 = FLR_BOSON_DUAL_GAIN
rawBoson -p/dev/ttyAMC0 -b921600 c00050014 x0 x0 x0 x4 = FLR_BOSON_MANUAL_GAIN
rawBoson -p/dev/ttyAMC0 -b921600 c00050014 x0 x0 x0 x5 = FLR_BOSON_GAINMODE_END 
 
![Screenshot from 2021-02-10 23-55-22](https://user-images.githubusercontent.com/38882830/107585627-4994ee00-6c07-11eb-8f86-974358c83aff.png)
![Screenshot from 2021-02-11 00-31-37](https://user-images.githubusercontent.com/38882830/107585639-4ef23880-6c07-11eb-8df6-b789373841fe.png)

**Comment by ghost** [comment]
You got it, i didn't have time to answer you !
Exactly that is the right document , and rawBoson is just a basic interface to trigger the commands.
Our recommendation for integrations is to use the SDK that goes with Boson, in the sense that is more readable and helps using the camera since for complicated actions offers just a function call. 
I am going to put that LINK in the README file.  Happy to see that it is working for you

**Comment by ahmedosama9777** [comment]
Thank you, mate!
